/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LedgerChartOfAccounts { 
    account_name?: string;
    category_id?: number;
    description?: string;
    parent_category_id?: number;
}