/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SendMessageRequest { 
    to: string;
    from: string;
    text?: string;
    template_id?: number;
    template_arguments?: Array<string>;
}