/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    first_name?: string;
    last_name?: string;
    propio_user_id?: number;
    auth0_user_id?: string;
    email?: string;
    sms_phone?: string;
    whatsapp_phone?: string;
    onboarded?: boolean;
    user_type?: string;
    picture?: any;
    partner_id?: number;
}