/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankAccount } from './bankAccount';
import { BankAccountMapping } from './bankAccountMapping';
import { LedgerAccount } from './ledgerAccount';

export interface BankAccountMappingResult { 
    mappings?: Array<BankAccountMapping>;
    /**
     * The bank accounts that this client has connected.
     */
    bank_accounts?: Array<BankAccount>;
    ledger_bank_accounts?: Array<LedgerAccount>;
}