/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Ledger-specific account data. This type will not have specific members. Each ledger will populate this object with their corresponding fields. Normally, this will contain all the fields from a call to get the account details.
 */
export interface LedgerAccountData { 
}