/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Client } from './client';

export interface Organization { 
    organization_id?: number;
    name?: string;
    web_url?: string;
    logo_url?: string;
    industry?: string;
    is_bank_connected?: boolean;
    is_quickbooks_connected?: boolean;
    is_onboarded?: boolean;
    client_point_of_contact?: Client;
}