/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Partner { 
    partner_id?: number;
    contact_first_name?: string;
    contact_last_name?: string;
    contact_email?: string;
    whatsapp_identity?: string;
    whatsapp_phone_number?: string;
    sender_email?: string;
    organization_id?: number;
    onboarded?: boolean;
}