/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Organization } from './organization';
import { User } from './user';

/**
 * Represents a request to onboard an user. Relies on existing User and Organization types
 */
export interface PartnerOnboardingRequest { 
    user: User;
    organization: Organization;
}