/**
 * Propio API
 * Microservice for partner managment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AiSuggestion } from './aiSuggestion';

export interface Transaction { 
    transaction_id?: number;
    date?: string;
    amount?: string;
    categorization_status?: string;
    city_state?: string;
    transaction_category_id?: string;
    suggestion_transaction_category_id?: string;
    feedback_requests?: string;
    logo_url?: string;
    merchant_name?: string;
    original_description?: string;
    account_friendly_name?: string;
    plaid_transaction_id?: string;
    qbo_realm_id?: string;
    /**
     * An ID representing the transaction in a ledger. IT's different per ledger and per propio version.
     */
    ledger_transaction_id?: any;
    ledger_id?: number;
    ai_suggestion?: AiSuggestion;
}